# Generated by Django 5.1.5 on 2025-01-15 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skelbimas',
            name='skelbimoTipas',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
