# Generated by Django 5.1.5 on 2025-01-16 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_skelbimas_skelbimotipas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skelbimas',
            old_name='bvpzkodas',
            new_name='bvpzKodas',
        ),
    ]
